export interface NodeDef {
  label: string;
  emoji: string;
  /** Hex color for the node header. */
  color: string;
  /** Tailwind bg class — must be listed statically for JIT. */
  bgClass: string;
  category: 'Mail' | 'Excel' | 'Folder' | 'Logic' | 'Browser' | 'Integration';
  /** Short description shown in the toolbox. */
  description?: string;
  defaultConfig: Record<string, unknown>;
}

export const NODE_DEFS: Record<string, NodeDef> = {
  'mail.read-attachments': {
    label: 'Mail Receive',
    emoji: '📧',
    color: '#2563eb',
    bgClass: 'bg-blue-600',
    category: 'Mail',
    defaultConfig: {
      folder: 'INBOX',
      subjectContains: '',
      fromContains: '',
      unreadOnly: true,
      latestOnly: true,
      maxCount: 1,
      sortOrder: 'newest',
      attachmentNameContains: '',
      attachmentPattern: '*.xlsx',
      markAsReadAfterProcessing: false,
      artifactPrefix: 'mail-file',
      outputVariable: 'mailArtifacts',
    },
  },
  'mail.send': {
    label: 'Mail Send',
    emoji: '📤',
    color: '#4f46e5',
    bgClass: 'bg-indigo-600',
    category: 'Mail',
    defaultConfig: {
      to: '',
      cc: '',
      bcc: '',
      subject: 'AlterOne Process Completed',
      body: 'The workflow completed successfully.',
      isHtml: false,
      attachments: '',
    },
  },
  'mail.get-body': {
    label: 'Mail Get Body',
    emoji: '📄',
    color: '#2563eb',
    bgClass: 'bg-blue-600',
    category: 'Mail',
    defaultConfig: {
      bodyType: 'html',
      outputVariable: 'mailBody',
      sourceVariable: 'receivedMails',
      messageIndex: 0,
      messageId: '',
      folder: '',
    },
  },
  'mail.extract-value': {
    label: 'Mail Extract Value',
    emoji: '🔎',
    color: '#1d4ed8',
    bgClass: 'bg-blue-700',
    category: 'Mail',
    defaultConfig: {
      sourceVariable: 'mailBody',
      label: 'Tutar',
      pattern: '',
      outputVariable: 'amount',
    },
  },
  'mail.extract-table': {
    label: 'Mail Extract Table',
    emoji: '📋',
    color: '#1d4ed8',
    bgClass: 'bg-blue-700',
    category: 'Mail',
    defaultConfig: {
      sourceVariable: 'mailBody',
      tableIndex: 0,
      mode: 'cell',
      rowIndex: 1,
      columnIndex: 1,
      lookupColumn: '',
      lookupValue: '',
      returnColumn: '',
      outputVariable: 'tableValue',
      ignoreCase: true,
    },
  },
  'mail.reply': {
    label: 'Mail Reply',
    emoji: '↩️',
    color: '#2563eb',
    bgClass: 'bg-blue-600',
    category: 'Mail',
    defaultConfig: {
      messageId: '{{selectedMessageId}}',
      body: 'Your request has been processed.',
      replyAll: false,
      includeOriginalBody: true,
      isHtml: false,
      attachments: '',
      sourceFolder: '',
    },
  },
  'mail.forward': {
    label: 'Mail Forward',
    emoji: '➡️',
    color: '#2563eb',
    bgClass: 'bg-blue-600',
    category: 'Mail',
    defaultConfig: {
      messageId: '{{selectedMessageId}}',
      to: '',
      cc: '',
      bcc: '',
      body: 'Please review.',
      includeAttachments: true,
      isHtml: false,
      sourceFolder: '',
    },
  },
  'mail.move': {
    label: 'Mail Move',
    emoji: '📁',
    color: '#2563eb',
    bgClass: 'bg-blue-600',
    category: 'Mail',
    defaultConfig: {
      messageId: '{{selectedMessageId}}',
      targetFolder: 'Processed',
      sourceFolder: '',
    },
  },
  'mail.mark': {
    label: 'Mail Mark Read/Unread',
    emoji: '✉️',
    color: '#2563eb',
    bgClass: 'bg-blue-600',
    category: 'Mail',
    defaultConfig: {
      messageId: '{{selectedMessageId}}',
      isRead: true,
      sourceFolder: '',
    },
  },
  'mail.delete': {
    label: 'Mail Delete',
    emoji: '🗑️',
    color: '#dc2626',
    bgClass: 'bg-red-600',
    category: 'Mail',
    defaultConfig: {
      messageId: '{{selectedMessageId}}',
      permanent: false,
      sourceFolder: '',
    },
  },
  'excel.read': {
    label: 'Excel Read',
    emoji: '📊',
    color: '#059669',
    bgClass: 'bg-emerald-600',
    category: 'Excel',
    defaultConfig: {
      artifactName: '',
      sheetName: 'Sheet1',
      hasHeaderRow: 'true',
      outputVariable: 'excelData',
    },
  },
  'excel.read-range': {
    label: 'Excel Read Range',
    emoji: '📋',
    color: '#047857',
    bgClass: 'bg-emerald-700',
    category: 'Excel',
    defaultConfig: {
      inputArtifactName: 'source-file',
      sheetName: 'Data',
      range: 'A1:D100',
      hasHeader: true,
      outputVariable: 'dataTable',
      trimValues: true,
      includeEmptyRows: false,
    },
  },
  'excel.write-datatable': {
    label: 'Excel Write DataTable',
    emoji: '📝',
    color: '#059669',
    bgClass: 'bg-emerald-600',
    category: 'Excel',
    defaultConfig: {
      inputArtifactName:   'report.xlsx',
      sheetName:           'Customers',
      sourceVariable:      'sqlResult',
      startCell:           'A1',
      includeHeaders:      true,
      clearExistingData:   false,
      createSheetIfMissing: true,
    },
  },
  'excel.append-datatable': {
    label: 'Excel Append DataTable',
    emoji: '➕',
    color: '#0d9488',
    bgClass: 'bg-teal-600',
    category: 'Excel',
    defaultConfig: {
      inputArtifactName:     'history.xlsx',
      sheetName:             'History',
      sourceVariable:        'sqlResult',
      createSheetIfMissing:  true,
      includeHeadersIfEmpty: true,
      matchColumnsByName:    true,
    },
  },
  'excel.transform': {
    label: 'Excel Transform',
    emoji: '🔄',
    color: '#d97706',
    bgClass: 'bg-amber-600',
    category: 'Excel',
    defaultConfig: {
      inputArtifactName: 'source-file',
      outputName: 'transformed-excel',
      operations: [
        {
          type: 'insertColumn',
          sheetName: 'Data',
          afterColumn: 'B',
          newColumn: 'C',
          header: 'New Column',
        },
        {
          type: 'copyColumn',
          sourceSheet: 'Data',
          sourceColumn: 'B',
          targetSheet: 'Data',
          targetColumn: 'C',
          targetHeader: 'Copied B',
        },
        {
          type: 'convertColumnToNumber',
          sheetName: 'Data',
          column: 'C',
          startRow: 2,
          numberFormat: '#,##0.00',
        },
      ],
    },
  },
  'excel.merge': {
    label: 'Excel Merge',
    emoji: '📎',
    color: '#0284c7',
    bgClass: 'bg-sky-600',
    category: 'Excel',
    defaultConfig: {
      inputArtifactNames: ['file1.xlsx', 'file2.xlsx'],
      outputName: 'merged-excel',
      sourceSheetName: 'Data',
      targetSheetName: 'Merged',
      includeHeaderOnce: true,
      startRow: 1,
    },
  },
  'excel.split': {
    label: 'Excel Split',
    emoji: '✂️',
    color: '#0284c7',
    bgClass: 'bg-sky-600',
    category: 'Excel',
    defaultConfig: {
      inputArtifactName: 'source-file',
      sourceSheetName: 'Data',
      splitColumn: 'Region',
      outputNamePattern: 'split-{value}.xlsx',
      includeHeader: true,
      startRow: 2,
    },
  },
  'folder.read-file': {
    label: 'Folder Read',
    emoji: '📂',
    color: '#7c3aed',
    bgClass: 'bg-violet-600',
    category: 'Folder',
    defaultConfig: {
      sourcePath: '{{triggerFilePath}}',
      artifactName: 'source-file',
    },
  },
  'folder.write-file': {
    label: 'Folder Write',
    emoji: '💾',
    color: '#db2777',
    bgClass: 'bg-pink-600',
    category: 'Folder',
    defaultConfig: {
      artifactName: 'transformed-excel.xlsx',
      destinationPath: 'C:\\Temp\\AlterOneOutput\\transformed-excel.xlsx',
      overwrite: true,
    },
  },
  'folder.list-files': {
    label: 'Folder List Files',
    emoji: '📋',
    color: '#059669',
    bgClass: 'bg-emerald-600',
    category: 'Folder',
    defaultConfig: {
      folderPath: 'C:\\Reports',
      searchPattern: '*.xlsx',
      recursive: false,
      outputVariable: 'files',
    },
  },
  'csv.read': {
    label: 'CSV Read',
    emoji: '📄',
    color: '#d97706',
    bgClass: 'bg-amber-600',
    category: 'Folder',
    defaultConfig: {
      inputArtifactName: 'source-file',
      delimiter: ',',
      customDelimiter: ',',
      encoding: 'UTF-8',
      hasHeader: true,
      outputVariable: 'csvData',
      trimValues: true,
      includeEmptyRows: false,
    },
  },
  'csv.write': {
    label: 'CSV Write',
    emoji: '💾',
    color: '#b45309',
    bgClass: 'bg-amber-700',
    category: 'Folder',
    defaultConfig: {
      sourceVariable: 'csvData',
      outputName: 'output.csv',
      delimiter: ',',
      customDelimiter: ',',
      encoding: 'UTF-8',
      includeHeaders: true,
      quoteValues: true,
    },
  },
  'json.read-file': {
    label: 'JSON Read File',
    emoji: '{ }',
    color: '#6d28d9',
    bgClass: 'bg-violet-700',
    category: 'Folder',
    defaultConfig: {
      inputArtifactName: 'source-file',
      path: '$.items',
      outputVariable: 'jsonData',
      outputMode: 'json',
    },
  },
  'json.write-file': {
    label: 'JSON Write File',
    emoji: '📝',
    color: '#4338ca',
    bgClass: 'bg-indigo-700',
    category: 'Folder',
    defaultConfig: {
      sourceVariable: 'apiResult_body',
      outputName: 'output.json',
      prettyPrint: true,
    },
  },
  'zip.extract': {
    label: 'ZIP Extract',
    emoji: '📦',
    color: '#7c2d12',
    bgClass: 'bg-orange-900',
    category: 'Folder',
    defaultConfig: {
      inputArtifactName: 'reports.zip',
      outputPrefix: 'unzipped',
      filterPattern: '*.xlsx',
      overwrite: true,
      failIfNoMatches: false,
      outputVariable: 'extractedFiles',
    },
  },
  'zip.create': {
    label: 'ZIP Create',
    emoji: '🗜',
    color: '#c2410c',
    bgClass: 'bg-orange-700',
    category: 'Folder',
    defaultConfig: {
      inputArtifactNames: ['report.xlsx', 'summary.csv'],
      outputName: 'reports.zip',
      compressionLevel: 'optimal',
    },
  },
  'pdf.read-text': {
    label: 'PDF Read Text',
    emoji: '📕',
    color: '#be123c',
    bgClass: 'bg-rose-700',
    category: 'Folder',
    defaultConfig: {
      inputArtifactName: 'invoice.pdf',
      pageRange: '',
      outputVariable: 'pdfText',
      normalizeWhitespace: true,
      failIfEmpty: false,
    },
  },
  'pdf.extract-table': {
    label: 'PDF Extract Table',
    emoji: '📊',
    color: '#be123c',
    bgClass: 'bg-rose-700',
    category: 'Folder',
    defaultConfig: {
      inputArtifactName: 'report.pdf',
      pageRange: '',
      tableIndex: 0,
      parserMode: 'auto',
      delimiter: '',
      hasHeader: true,
      outputVariable: 'pdfTable',
      normalizeWhitespace: true,
      failIfNoTable: true,
    },
  },
  'word.fill-template': {
    label: 'Word Template Fill',
    emoji: '📝',
    color: '#1d4ed8',
    bgClass: 'bg-blue-700',
    category: 'Folder',
    defaultConfig: {
      inputArtifactName: 'template.docx',
      outputName: 'generated.docx',
      strictMode: false,
      outputVariable: 'generatedDocument',
    },
  },
  'condition.if': {
    label: 'Condition (IF)',
    emoji: '◆',
    color: '#ea580c',
    bgClass: 'bg-orange-600',
    category: 'Logic',
    defaultConfig: {
      condition: {
        left: '',
        operator: 'exists',
        right: '',
      },
    },
  },
  'set.variable': {
    label: 'Set Variable',
    emoji: '📝',
    color: '#9333ea',
    bgClass: 'bg-purple-600',
    category: 'Logic',
    defaultConfig: {
      variableName: '',
      value: '',
      valueType: 'string',
      mode: 'literal',
    },
  },
  'foreach.loop': {
    label: 'For Each',
    emoji: '⟳',
    color: '#0891b2',
    bgClass: 'bg-cyan-600',
    category: 'Logic',
    defaultConfig: {
      collection:    '{{mailArtifacts}}',
      itemVariable:  'currentItem',
      indexVariable: 'currentIndex',
    },
  },
  'foreach.row': {
    label: 'For Each Row',
    emoji: '⟳',
    color: '#0e7490',
    bgClass: 'bg-cyan-700',
    category: 'Logic',
    defaultConfig: {
      collectionVariable: 'dataTable',
      rowVariable:        'currentRow',
      indexVariable:      'currentIndex',
    },
  },
  'foreach.file': {
    label: 'For Each File',
    emoji: '⟳',
    color: '#047857',
    bgClass: 'bg-emerald-700',
    category: 'Logic',
    defaultConfig: {
      collectionVariable: 'files',
      fileVariable:       'currentFile',
      indexVariable:      'currentIndex',
    },
  },
  'datatable.aggregate': {
    label: 'DataTable Aggregate',
    emoji: 'Σ',
    color: '#7c3aed',
    bgClass: 'bg-violet-600',
    category: 'Logic',
    defaultConfig: {
      sourceVariable: 'dataTable',
      operation:      'sum',
      column:         'Amount',
      outputVariable: 'totalAmount',
      ignoreEmpty:    true,
    },
  },
  'datatable.join': {
    label: 'DataTable Join',
    emoji: '⛓',
    color: '#4f46e5',
    bgClass: 'bg-indigo-600',
    category: 'Logic',
    defaultConfig: {
      leftVariable:      'ordersTable',
      rightVariable:     'customersTable',
      leftKeyColumns:    ['CustomerNo'],
      rightKeyColumns:   ['CustomerNo'],
      joinType:          'left',
      rightColumnsToAdd: [
        { sourceColumn: 'CustomerName', targetColumn: 'CustomerName' },
        { sourceColumn: 'Region', targetColumn: 'CustomerRegion' },
      ],
      outputVariable: 'joinedTable',
      notFoundValue:  '',
      ignoreCase:     true,
      trimValues:     true,
    },
  },
  'http.request': {
    label: 'HTTP Request',
    emoji: '🌐',
    color: '#0284c7',
    bgClass: 'bg-sky-600',
    category: 'Integration',
    defaultConfig: {
      url:                    'https://jsonplaceholder.typicode.com/users',
      method:                 'GET',
      headers:                {},
      queryParameters:        {},
      body:                   '',
      contentType:            'application/json',
      timeoutSeconds:         60,
      failOnNonSuccessStatus: true,
      bearerTokenCredentialName: '',
      apiKeyCredentialName:      '',
      apiKeyHeaderName:          'X-Api-Key',
      outputVariable:         'apiResult',
    },
  },
  'json.parse': {
    label: 'JSON Parse',
    emoji: '{ }',
    color: '#7c3aed',
    bgClass: 'bg-violet-600',
    category: 'Integration',
    defaultConfig: {
      sourceVariable: 'apiResult_body',
      path:           '$[0].name',
      outputVariable: 'firstUserName',
      outputMode:     'value',
    },
  },
  'sql.query': {
    label: 'SQL Query',
    emoji: '🗄',
    color: '#059669',
    bgClass: 'bg-emerald-600',
    category: 'Integration',
    defaultConfig: {
      connectionString: '',
      connectionName:   '',
      query:            'SELECT TOP 3 CustomerNo, CustomerName FROM Customers',
      parameters:       {},
      timeoutSeconds:   60,
      outputVariable:   'sqlResult',
    },
  },
  'sql.execute': {
    label: 'SQL Execute',
    emoji: '✏️',
    color: '#0284c7',
    bgClass: 'bg-sky-600',
    category: 'Integration',
    defaultConfig: {
      connectionString: '',
      connectionName:   '',
      sql:              "UPDATE Customers SET Status = @status WHERE CustomerNo = @customerNo",
      parameters:       [
        { name: 'status', value: 'Processed' },
        { name: 'customerNo', value: '{{currentRow.CustomerNo}}' },
      ],
      timeoutSeconds: 300,
    },
  },
  'sql.stored-procedure': {
    label: 'SQL Stored Procedure',
    emoji: '⚙️',
    color: '#4f46e5',
    bgClass: 'bg-indigo-600',
    category: 'Integration',
    defaultConfig: {
      connectionString: '',
      connectionName:   '',
      procedureName:    'usp_ProcessCustomer',
      parameters:       [
        { name: 'CustomerNo', value: '{{currentRow.CustomerNo}}', direction: 'Input' },
      ],
      timeoutSeconds:   300,
      outputVariable:   'procResult',
    },
  },
  'browser.open': {
    label: 'Browser Open',
    emoji: '🌐',
    color: '#0d9488',
    bgClass: 'bg-teal-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      headless: true,
      viewportWidth: 1366,
      viewportHeight: 768,
    },
  },
  'browser.navigate': {
    label: 'Browser Navigate',
    emoji: '🔗',
    color: '#0f766e',
    bgClass: 'bg-teal-700',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      url: 'https://www.google.com',
    },
  },
  'browser.click': {
    label: 'Browser Click',
    emoji: '👆',
    color: '#14b8a6',
    bgClass: 'bg-teal-500',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
    },
  },
  'browser.type': {
    label: 'Browser Type',
    emoji: '⌨️',
    color: '#2dd4bf',
    bgClass: 'bg-teal-400',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
      text: '',
    },
  },
  'browser.wait-for-selector': {
    label: 'Browser Wait',
    emoji: '⏳',
    color: '#115e59',
    bgClass: 'bg-teal-800',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
      timeoutMs: 30000,
    },
  },
  'browser.get-text': {
    label: 'Browser Get Text',
    emoji: '📝',
    color: '#5eead4',
    bgClass: 'bg-teal-300',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
      outputVariable: 'browserText',
    },
  },
  'browser.get-attribute': {
    label: 'Browser Get Attribute',
    emoji: '🏷️',
    color: '#99f6e4',
    bgClass: 'bg-teal-200',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
      attribute: 'href',
      outputVariable: 'browserAttribute',
    },
  },
  'browser.screenshot': {
    label: 'Browser Screenshot',
    emoji: '📸',
    color: '#134e4a',
    bgClass: 'bg-teal-900',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      artifactName: 'browser-screenshot',
    },
  },
  'browser.download': {
    label: 'Browser Download',
    emoji: '⬇️',
    color: '#042f2e',
    bgClass: 'bg-teal-950',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      clickSelector: '',
      artifactName: 'downloaded-file',
    },
  },
  'browser.press-key': {
    label: 'Browser Press Key',
    emoji: '⌨️',
    color: '#0891b2',
    bgClass: 'bg-cyan-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
      key: 'Enter',
    },
  },
  'browser.clear': {
    label: 'Browser Clear Field',
    emoji: '🧹',
    color: '#06b6d4',
    bgClass: 'bg-cyan-500',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
    },
  },
  'browser.scroll': {
    label: 'Browser Scroll',
    emoji: '↕️',
    color: '#0d9488',
    bgClass: 'bg-teal-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
      direction: 'down',
      amount: 1000,
    },
  },
  'browser.select': {
    label: 'Browser Select Dropdown',
    emoji: '📋',
    color: '#0ea5e9',
    bgClass: 'bg-sky-500',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
      mode: 'value',
      value: '',
      label: '',
      index: 0,
    },
  },
  'browser.hover': {
    label: 'Browser Hover',
    emoji: '🖱️',
    color: '#14b8a6',
    bgClass: 'bg-teal-500',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
    },
  },
  'browser.wait-url': {
    label: 'Browser Wait URL',
    emoji: '🔗',
    color: '#0369a1',
    bgClass: 'bg-sky-700',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      urlContains: '',
      matchMode: 'contains',
      timeoutMs: 30000,
    },
  },
  'browser.wait-text': {
    label: 'Browser Wait Text',
    emoji: '🔍',
    color: '#0284c7',
    bgClass: 'bg-sky-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      text: '',
      selector: '',
      timeoutMs: 30000,
    },
  },
  'browser.wait-download': {
    label: 'Browser Wait Download',
    emoji: '📥',
    color: '#155e75',
    bgClass: 'bg-cyan-800',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      clickSelector: '',
      artifactName: 'downloaded-file',
      timeoutMs: 60000,
    },
  },
  'browser.wait-network-idle': {
    label: 'Browser Wait Network Idle',
    emoji: '⏳',
    color: '#475569',
    bgClass: 'bg-slate-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      timeoutMs: 30000,
    },
  },
  'browser.element-exists': {
    label: 'Browser Element Exists',
    emoji: '✓',
    color: '#059669',
    bgClass: 'bg-emerald-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
      timeoutMs: 5000,
      visibleOnly: true,
      outputVariable: 'elementExists',
    },
  },
  'browser.upload-file': {
    label: 'Browser Upload File',
    emoji: '📤',
    color: '#0f766e',
    bgClass: 'bg-teal-700',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: "input[type='file']",
      artifactName: '',
      filePath: '',
      timeoutMs: 30000,
    },
  },
  'browser.switch-tab': {
    label: 'Browser Switch Tab',
    emoji: '🗂️',
    color: '#6366f1',
    bgClass: 'bg-indigo-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      mode: 'last',
      urlContains: '',
      titleContains: '',
      timeoutMs: 30000,
    },
  },
  'browser.close-tab': {
    label: 'Browser Close Tab',
    emoji: '✕',
    color: '#64748b',
    bgClass: 'bg-slate-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      mode: 'current',
    },
  },
  'browser.handle-alert': {
    label: 'Browser Handle Alert',
    emoji: '💬',
    color: '#f59e0b',
    bgClass: 'bg-amber-500',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      action: 'accept',
      promptText: '',
      clickSelector: '',
      timeoutMs: 30000,
    },
  },
  'browser.wait-popup': {
    label: 'Browser Wait Popup',
    emoji: '🪟',
    color: '#8b5cf6',
    bgClass: 'bg-violet-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      clickSelector: '',
      timeoutMs: 30000,
      switchToPopup: true,
    },
  },
  'browser.click-and-handle-alert': {
    label: 'Browser Click And Handle Alert',
    emoji: '💬',
    color: '#d97706',
    bgClass: 'bg-amber-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      clickSelector: '',
      action: 'accept',
      promptText: '',
      timeoutMs: 30000,
    },
  },
  'browser.extract-table': {
    label: 'Browser Extract Table',
    emoji: '📋',
    color: '#059669',
    bgClass: 'bg-emerald-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      mode: 'htmlTable',
      selector: 'table',
      tableIndex: 0,
      rowSelector: '',
      cellSelector: '',
      outputVariable: 'webTable',
      includeHeaders: true,
      skipEmptyRows: true,
      normalizeWhitespace: true,
      timeoutMs: 30000,
    },
  },
  'browser.wait-for-text': {
    label: 'Browser Wait For Text',
    emoji: '🔍',
    color: '#0284c7',
    bgClass: 'bg-sky-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      text: '',
      timeoutMs: 30000,
    },
  },
  'browser.wait-for-url': {
    label: 'Browser Wait For URL',
    emoji: '🔗',
    color: '#0369a1',
    bgClass: 'bg-sky-700',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      urlContains: '',
      timeoutMs: 30000,
    },
  },
  'browser.select-option': {
    label: 'Browser Select Option',
    emoji: '📋',
    color: '#0ea5e9',
    bgClass: 'bg-sky-500',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      selector: '',
      value: '',
      label: '',
    },
  },
  'browser.evaluate': {
    label: 'Browser Evaluate',
    emoji: '🧪',
    color: '#7c3aed',
    bgClass: 'bg-violet-600',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      script: '',
      outputVariable: 'browserEvalResult',
    },
  },
  'browser.wait-for-download': {
    label: 'Browser Wait For Download',
    emoji: '📥',
    color: '#155e75',
    bgClass: 'bg-cyan-800',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
      clickSelector: '',
      artifactName: 'downloaded-file',
    },
  },
  'browser.close': {
    label: 'Browser Close',
    emoji: '🚪',
    color: '#64748b',
    bgClass: 'bg-slate-500',
    category: 'Browser',
    defaultConfig: {
      sessionName: 'default',
    },
  },
};

/** Ordered list for the toolbox panel. */
export const TOOLBOX_ITEMS: Array<{ stepType: string } & NodeDef> = [
  { stepType: 'mail.read-attachments', ...NODE_DEFS['mail.read-attachments'] },
  { stepType: 'mail.get-body',         ...NODE_DEFS['mail.get-body'] },
  { stepType: 'mail.extract-value',    ...NODE_DEFS['mail.extract-value'] },
  { stepType: 'mail.extract-table',    ...NODE_DEFS['mail.extract-table'] },
  { stepType: 'mail.send',             ...NODE_DEFS['mail.send'] },
  { stepType: 'mail.reply',            ...NODE_DEFS['mail.reply'] },
  { stepType: 'mail.forward',          ...NODE_DEFS['mail.forward'] },
  { stepType: 'mail.move',             ...NODE_DEFS['mail.move'] },
  { stepType: 'mail.mark',             ...NODE_DEFS['mail.mark'] },
  { stepType: 'mail.delete',           ...NODE_DEFS['mail.delete'] },
  { stepType: 'excel.read',            ...NODE_DEFS['excel.read'] },
  { stepType: 'excel.read-range',      ...NODE_DEFS['excel.read-range'] },
  { stepType: 'excel.write-datatable', ...NODE_DEFS['excel.write-datatable'] },
  { stepType: 'excel.append-datatable', ...NODE_DEFS['excel.append-datatable'] },
  { stepType: 'excel.transform',       ...NODE_DEFS['excel.transform'] },
  { stepType: 'excel.merge',           ...NODE_DEFS['excel.merge'] },
  { stepType: 'excel.split',           ...NODE_DEFS['excel.split'] },
  { stepType: 'folder.read-file',      ...NODE_DEFS['folder.read-file'] },
  { stepType: 'folder.write-file',     ...NODE_DEFS['folder.write-file'] },
  { stepType: 'folder.list-files',     ...NODE_DEFS['folder.list-files'] },
  { stepType: 'csv.read',              ...NODE_DEFS['csv.read'] },
  { stepType: 'csv.write',             ...NODE_DEFS['csv.write'] },
  { stepType: 'json.read-file',         ...NODE_DEFS['json.read-file'] },
  { stepType: 'json.write-file',         ...NODE_DEFS['json.write-file'] },
  { stepType: 'zip.extract',             ...NODE_DEFS['zip.extract'] },
  { stepType: 'zip.create',              ...NODE_DEFS['zip.create'] },
  { stepType: 'pdf.read-text',           ...NODE_DEFS['pdf.read-text'] },
  { stepType: 'pdf.extract-table',       ...NODE_DEFS['pdf.extract-table'] },
  { stepType: 'word.fill-template',      ...NODE_DEFS['word.fill-template'] },
  { stepType: 'condition.if',          ...NODE_DEFS['condition.if'] },
  { stepType: 'set.variable',          ...NODE_DEFS['set.variable'] },
  { stepType: 'foreach.loop',          ...NODE_DEFS['foreach.loop'] },
  { stepType: 'foreach.row',           ...NODE_DEFS['foreach.row'] },
  { stepType: 'foreach.file',          ...NODE_DEFS['foreach.file'] },
  { stepType: 'datatable.aggregate',   ...NODE_DEFS['datatable.aggregate'] },
  { stepType: 'datatable.join',        ...NODE_DEFS['datatable.join'] },
  { stepType: 'http.request',          ...NODE_DEFS['http.request'] },
  { stepType: 'json.parse',            ...NODE_DEFS['json.parse'] },
  { stepType: 'sql.query',             ...NODE_DEFS['sql.query'] },
  { stepType: 'sql.execute',           ...NODE_DEFS['sql.execute'] },
  { stepType: 'sql.stored-procedure',  ...NODE_DEFS['sql.stored-procedure'] },
  { stepType: 'browser.open',            ...NODE_DEFS['browser.open'] },
  { stepType: 'browser.navigate',        ...NODE_DEFS['browser.navigate'] },
  { stepType: 'browser.click',           ...NODE_DEFS['browser.click'] },
  { stepType: 'browser.type',            ...NODE_DEFS['browser.type'] },
  { stepType: 'browser.wait-for-selector', ...NODE_DEFS['browser.wait-for-selector'] },
  { stepType: 'browser.get-text',        ...NODE_DEFS['browser.get-text'] },
  { stepType: 'browser.get-attribute',   ...NODE_DEFS['browser.get-attribute'] },
  { stepType: 'browser.screenshot',      ...NODE_DEFS['browser.screenshot'] },
  { stepType: 'browser.download',        ...NODE_DEFS['browser.download'] },
  { stepType: 'browser.press-key',       ...NODE_DEFS['browser.press-key'] },
  { stepType: 'browser.clear',           ...NODE_DEFS['browser.clear'] },
  { stepType: 'browser.scroll',          ...NODE_DEFS['browser.scroll'] },
  { stepType: 'browser.select',          ...NODE_DEFS['browser.select'] },
  { stepType: 'browser.hover',           ...NODE_DEFS['browser.hover'] },
  { stepType: 'browser.wait-url',        ...NODE_DEFS['browser.wait-url'] },
  { stepType: 'browser.wait-text',       ...NODE_DEFS['browser.wait-text'] },
  { stepType: 'browser.wait-download',   ...NODE_DEFS['browser.wait-download'] },
  { stepType: 'browser.wait-network-idle', ...NODE_DEFS['browser.wait-network-idle'] },
  { stepType: 'browser.element-exists',  ...NODE_DEFS['browser.element-exists'] },
  { stepType: 'browser.upload-file',     ...NODE_DEFS['browser.upload-file'] },
  { stepType: 'browser.switch-tab',      ...NODE_DEFS['browser.switch-tab'] },
  { stepType: 'browser.close-tab',       ...NODE_DEFS['browser.close-tab'] },
  { stepType: 'browser.handle-alert',    ...NODE_DEFS['browser.handle-alert'] },
  { stepType: 'browser.wait-popup',      ...NODE_DEFS['browser.wait-popup'] },
  { stepType: 'browser.click-and-handle-alert', ...NODE_DEFS['browser.click-and-handle-alert'] },
  { stepType: 'browser.extract-table',     ...NODE_DEFS['browser.extract-table'] },
  { stepType: 'browser.wait-for-text',   ...NODE_DEFS['browser.wait-for-text'] },
  { stepType: 'browser.wait-for-url',    ...NODE_DEFS['browser.wait-for-url'] },
  { stepType: 'browser.select-option',   ...NODE_DEFS['browser.select-option'] },
  { stepType: 'browser.evaluate',        ...NODE_DEFS['browser.evaluate'] },
  { stepType: 'browser.wait-for-download', ...NODE_DEFS['browser.wait-for-download'] },
  { stepType: 'browser.close',           ...NODE_DEFS['browser.close'] },
];

/** Short descriptions for toolbox cards (fallback when NodeDef.description is absent). */
export const NODE_DESCRIPTIONS: Record<string, string> = {
  'mail.read-attachments':   'Download email attachments as artifacts',
  'mail.get-body':           'Fetch full email body text or HTML',
  'mail.extract-value':      'Extract a labeled or regex value from text',
  'mail.extract-table':      'Extract cells or rows from HTML tables in email body',
  'mail.send':                 'Send email with optional attachments',
  'mail.reply':                'Reply to an email and preserve the thread',
  'mail.forward':              'Forward an email to new recipients',
  'mail.move':                 'Move an email to another folder',
  'mail.mark':                 'Mark an email as read or unread',
  'mail.delete':               'Delete an email or move to Deleted Items',
  'excel.read':                'Read sheet rows into a JSON variable',
  'excel.read-range':          'Read an Excel range into a DataTable variable',
  'excel.write-datatable':     'Write a DataTable variable into an Excel worksheet',
  'excel.append-datatable':    'Append DataTable rows to an existing Excel worksheet',
  'excel.transform':           'Apply column and sheet transformations',
  'excel.merge':               'Combine multiple workbooks into one sheet',
  'excel.split':               'Split rows into files by column value',
  'folder.read-file':          'Load a file from disk into an artifact',
  'folder.write-file':         'Save an artifact to a folder path',
  'folder.list-files':         'List matching files in a folder as a collection variable',
  'csv.read':                  'Read a CSV artifact into a DataTable variable',
  'csv.write':                 'Write a DataTable variable to a CSV artifact',
  'json.read-file':            'Read a JSON file artifact using JSON Path',
  'json.write-file':           'Write a workflow variable to a JSON file artifact',
  'zip.extract':               'Extract matching files from a ZIP artifact',
  'zip.create':                'Bundle multiple artifacts into a ZIP file',
  'pdf.read-text':             'Extract text from a PDF artifact (text-based PDFs only)',
  'pdf.extract-table':         'Extract a text-based table from a PDF into a DataTable variable',
  'word.fill-template':        'Generate a Word document from a template with placeholder replacement',
  'condition.if':              'Branch workflow on a true/false condition',
  'set.variable':              'Create or update a workflow variable (literal or expression)',
  'foreach.loop':              'Iterate over a collection variable',
  'foreach.row':               'Iterate over DataTable rows from Excel or mail table',
  'foreach.file':              'Iterate over file objects from folder.list-files',
  'datatable.aggregate':       'Calculate sum, count, average, min/max from a DataTable',
  'datatable.join':            'Join two DataTables on key columns like SQL lookup',
  'http.request':              'Call a REST API and store the response in variables',
  'json.parse':                'Extract values from JSON using JSON Path expressions',
  'sql.query':                 'Run a parameterized SELECT query against SQL Server',
  'sql.execute':               'Execute INSERT, UPDATE, DELETE, or MERGE statements',
  'sql.stored-procedure':      'Run a stored procedure with input/output parameters',
  'browser.open':              'Launch a browser session',
  'browser.navigate':          'Go to a URL in the browser',
  'browser.click':             'Click an element by selector',
  'browser.type':              'Type text into an input field',
  'browser.wait-for-selector': 'Wait until an element appears',
  'browser.get-text':          'Read text from an element',
  'browser.get-attribute':     'Read an attribute from an element',
  'browser.screenshot':        'Capture a screenshot artifact',
  'browser.download':          'Download a file via click',
  'browser.press-key':         'Press a keyboard key on the page or a focused element',
  'browser.clear':             'Clear an input or textarea field',
  'browser.scroll':            'Scroll the page or a specific element',
  'browser.select':            'Select an option in a dropdown by value, label, or index',
  'browser.hover':             'Hover the mouse over an element',
  'browser.wait-url':          'Wait until the page URL matches a pattern',
  'browser.wait-text':         'Wait until visible text appears on the page or in an element',
  'browser.wait-download':     'Click to trigger a download and wait for the file',
  'browser.wait-network-idle': 'Wait until the page network is idle',
  'browser.element-exists':    'Check if an element exists without failing',
  'browser.upload-file':       'Upload a workflow artifact or local file to a file input',
  'browser.switch-tab':        'Switch the active browser tab or popup',
  'browser.close-tab':         'Close a browser tab and switch to another',
  'browser.handle-alert':      'Accept or dismiss JavaScript alert/confirm/prompt dialogs',
  'browser.wait-popup':        'Click and wait for a popup window, optionally switch to it',
  'browser.click-and-handle-alert': 'Click an element and handle the dialog it triggers',
  'browser.extract-table':     'Extract HTML table or CSS grid data into a DataTable variable',
  'browser.wait-for-text':     'Wait until page contains text',
  'browser.wait-for-url':      'Wait until URL matches pattern',
  'browser.select-option':     'Select a dropdown option',
  'browser.evaluate':          'Run JavaScript in the page',
  'browser.wait-for-download': 'Wait for a file download',
  'browser.close':             'Close the browser session',
};
